### ISSUE TITLE
如果设置为“仅数字”那么一直显示0%

### ISSUE THREAD

**Issue by 100730088** [AzulEterno/Plugins-For-TrafficMonitor#1]
如果设置为“仅数字”那么一直显示0%

**Comment by AzulEterno** [comment]
> 如果设置为“仅数字”那么一直显示0%

能更加详细地说明一下问题吗？

**Comment by 100730088** [comment]
![image](https://user-images.githubusercontent.com/3375457/163741497-890da873-c46b-45e8-9329-8c854616c057.png)
![image](https://user-images.githubusercontent.com/3375457/163741666-46b32b94-e1f8-4dbd-a69e-8951cc3a0563.png)
任务栏如果选择“数字显示在图标旁边”那么就能正确显示电量%，如果选择“仅数字”那么很大概率只显示0%（如果问题不能重现的话，就把程序重启下试试）

**Comment by AzulEterno** [comment]
> 

阿哲？
我的电池功耗插件负责提供电池功耗+剩余电量+电池电压检测，那个图标插件是由原作者做的。。。
理论上插件之间是相互隔离的应该不是我的插件影响的。

**Comment by Sciroccogti** [comment]
> 阿哲？ 我的电池功耗插件负责提供电池功耗+剩余电量+电池电压检测，那个图标插件是由原作者做的。。。 理论上插件之间是相互隔离的应该不是我的插件影响的。

那您这边的插件能在任务栏直接显示电量百分比不？🥺

**Comment by AzulEterno** [comment]
> > 阿哲？ 我的电池功耗插件负责提供电池功耗+剩余电量+电池电压检测，那个图标插件是由原作者做的。。。 理论上插件之间是相互隔离的应该不是我的插件影响的。
> 
> 那您这边的插件能在任务栏直接显示电量百分比不？🥺

程序员根本原则就是分模块处理任务，他的模块我绝不做重复的部分。
