### ISSUE TITLE
Suggestion: another publish version that change text from "w" to "wat"

### ISSUE THREAD

**Issue by SHthemW** [AzulEterno/Plugins-For-TrafficMonitor#15]
Used to align with three letter long text
![img](https://github.com/AzulEterno/PowerMonPlugin-For-TrafficMonitor/assets/97659151/beddce13-a77e-486f-9036-846920aa30fd)
thanks very much =)

**Comment by AzulEterno** [comment]
Fixed in the newer version. Add customizable unit str.

![image](https://github.com/user-attachments/assets/6f94e8e6-db4b-4481-a82a-35ce05b7f6a0)
