### ISSUE TITLE
建议增加电池电压显示选项

### ISSUE THREAD

**Issue by AlbertWang2018** [AzulEterno/Plugins-For-TrafficMonitor#16]
目前电池充放电功率显示很好，希望能增加电压显示，因为我电池老化了，会跳水关机。
如果有电压显示，我就能提前知道电池快不行了。
目前我是用Aida64显示的电池电压，也能用。电池旧了内阻变大了，只办公看文档写文档能用两三个小时，如果突然cpu负载率超过50%电池电压会突然降低就自动关机了，撑不了20分钟。
(Get-WmiObject -Namespace root/wmi -Query "select * from batterystatus").voltage/1000
powershell里用上面代码可以获取电池电压

**Comment by AzulEterno** [comment]
其实是可以实现的，目前我的插件能获取电压数据。 我近期有时间的话会先把电池剩余时间和电压的选项端上来 然后适配一下Intel 平台功耗接口，然后暑假！
