### ISSUE TITLE
建议添加关闭启动的tip窗口选项，开机自启动每次都弹出来

### ISSUE THREAD

**Issue by k5nn5x** [AzulEterno/Plugins-For-TrafficMonitor#17]
建议添加关闭启动的tip窗口选项，开机自启动每次都弹出来

**Comment by AzulEterno** [comment]
关闭Debug设置按理说就不会有弹窗了。

**Comment by AzulEterno** [comment]
> 建议添加关闭启动的tip窗口选项，开机自启动每次都弹出来

更新了，修复了设置相关bug。欢迎再试试。

**Comment by k5nn5x** [comment]
之前我安装的是7月21的版本，现在安装最新版本没有那个问题了，但是还有另外一个问题就是获取cpu gpu功耗那个重启之后会关闭，导致智能显示功耗无法获取数据

**Comment by k5nn5x** [comment]
刚刚测试了一下，应该属于软件bug，跟之前的debug无法关闭一样，修改完设置需要退出软件再重启才能再下次开机的时候保存之前的配置
