### ISSUE TITLE
启动后无法自动加载设置

### ISSUE THREAD

**Issue by FrzMtrsprt** [AzulEterno/Plugins-For-TrafficMonitor#18]
每次启动后，CPU和GPU功耗统计总是显示Invalid；打开PowerMon设置点击确认后，才能正常显示功耗。
![{1666BD0A-B6CB-41B5-8C05-0350650007F0}](https://github.com/user-attachments/assets/3806b004-071f-49b8-8c24-a97dbfda49b7)

**Comment by AzulEterno** [comment]
我这里启动第一瞬间会显示Invalid，之后会正常。这是预期行为。 推测你可能使用的版本有不对应问题？ 如果有更多人提供更多信息会更好。

**Comment by FrzMtrsprt** [comment]
版本应该是没问题的，都是最新版

trafficmonitor：1.84.1 x64 (主分支2023.3.31编译版本）
LibreHardwareMonitorLib：0.9.3
PowerMon：1.3 x64

我在我的两台电脑上都能稳定复现这个问题，等待多久也不会恢复正常。会不会是因为这两台电脑都是核显？
而且所有设置好像都保存不上…？

**Comment by AzulEterno** [comment]
> 版本应该是没问题的，都是最新版
> 
> trafficmonitor：1.84.1 x64 (主分支2023.3.31编译版本） LibreHardwareMonitorLib：0.9.3 PowerMon：1.3 x64
> 
> 我在我的两台电脑上都能稳定复现这个问题，等待多久也不会恢复正常。会不会是因为这两台电脑都是核显？ 而且所有设置好像都保存不上…？

设置保存不上应该是主要问题 我近期会重新清理一下推送一个新版本。 稍后可以反馈

**Comment by FrzMtrsprt** [comment]
更新 https://github.com/AzulEterno/PowerMonPlugin-For-TrafficMonitor/commit/aed7c30273b812f4badc56673ae26359e6fd2e11 后，debug mode的设置仍然保存不上，而且`PowerMonPlugin.dll.ini`好像没有被写入过。
启动显示invalid的问题也没有解决。

**Comment by AzulEterno** [comment]
> 更新 [aed7c30](https://github.com/AzulEterno/PowerMonPlugin-For-TrafficMonitor/commit/aed7c30273b812f4badc56673ae26359e6fd2e11) 后，debug mode的设置仍然保存不上，而且`PowerMonPlugin.dll.ini`好像没有被写入过。 启动显示invalid的问题也没有解决。

尝试执行以下操作：
1. 检查插件保存目录的文件读写权限
2. 删除插件和插件配置文件
3. 重新安装插件，调整设置观察插件是否会生成配置。
4. 很重要的一点。只有安全退出TrafficMonitor的时候才会保存配置。使用强行停止或者运行报错可能不会保存配置。

**Comment by FrzMtrsprt** [comment]
> PowerMonPlugin.dll.ini好像没有被写入过

之前我忽略了trafficmonitor的设置保存位置是AppData，所以没有去看AppData目录下的`PowerMonPlugin.dll.ini`，但这个文件确实可以保存上设置，退出方式是点击右键菜单的“退出”。插件目录下也会创建`PowerMonPlugin.dll.ini`，内容为初始设置，但不会被更新。

是不是因为启动时插件加载的是插件目录下的配置文件，点击确认后才从AppData目录建在配置文件？

![{EFE2D187-9C72-46D3-A2FC-5F0AD5FF6F18}](https://github.com/user-attachments/assets/630e1dab-0702-4b84-a1ca-400189de3f1c)

**Comment by AzulEterno** [comment]
> > PowerMonPlugin.dll.ini好像没有被写入过
> 
> 之前我忽略了trafficmonitor的设置保存位置是AppData，所以没有去看AppData目录下的`PowerMonPlugin.dll.ini`，但这个文件确实可以保存上设置，退出方式是点击右键菜单的“退出”。插件目录下也会创建`PowerMonPlugin.dll.ini`，内容为初始设置，但不会被更新。
> 
> 是不是因为启动时插件加载的是插件目录下的配置文件，点击确认后才从AppData目录建在配置文件？
> 
> ![{EFE2D187-9C72-46D3-A2FC-5F0AD5FF6F18}](https://github.com/user-attachments/assets/630e1dab-0702-4b84-a1ca-400189de3f1c)
> 

我个人一直开启保存数据到目录下使用。如果你没有开启的话我可以朝着这个方向debug一下。保存数据位置的代码是没有动过的，按理说不会有问题

**Comment by AzulEterno** [comment]
> > PowerMonPlugin.dll.ini好像没有被写入过
> 
> 之前我忽略了trafficmonitor的设置保存位置是AppData，所以没有去看AppData目录下的`PowerMonPlugin.dll.ini`，但这个文件确实可以保存上设置，退出方式是点击右键菜单的“退出”。插件目录下也会创建`PowerMonPlugin.dll.ini`，内容为初始设置，但不会被更新。
> 
> 是不是因为启动时插件加载的是插件目录下的配置文件，点击确认后才从AppData目录建在配置文件？
> 
> ![{EFE2D187-9C72-46D3-A2FC-5F0AD5FF6F18}](https://private-user-images.githubusercontent.com/15852717/367363982-630e1dab-0702-4b84-a1ca-400189de3f1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzkyMDksIm5iZiI6MTcyNjI3ODkwOSwicGF0aCI6Ii8xNTg1MjcxNy8zNjczNjM5ODItNjMwZTFkYWItMDcwMi00Yjg0LWExY2EtNDAwMTg5ZGUzZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxNTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YjBkYzJlZjI5MjY0MjU2ZDkzZTUzMTczZjYxMzQzMWU4MmExMWEyOGY2MzI5YWJjNWQ4MmMzMzgzOWI3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TFsDUquwvjS8C5VINPbc2jKJqOZE2a3xVWs9_G-Z64g)

我自己尝试复现了，没用出现。你用的是带管理员权限的Traffic Monitor对吧？ 个人觉得这个似乎不是本程序的问题。如果可以的话你可以测试一下别的插件保存配置是否可用如何？

**Comment by FrzMtrsprt** [comment]
我尝试了自带的电量插件和[Haojia521的WeatherPro](https://github.com/Haojia521/TrafficMonitorPlugins)，均能在启动时加载原先的设置，插件配置文件也是被创建在了AppData目录，而不是插件文件目录。

![{48BE9894-AE48-4347-967F-BA7683D20C36}](https://github.com/user-attachments/assets/c6c68d84-eef3-426f-a761-972c92dbe2bd)
![{E0D59E0D-13F1-4CC0-B4B4-644F7C66E286}](https://github.com/user-attachments/assets/e730e6af-3f91-449e-8802-ab26de19c7d3)

**Comment by FrzMtrsprt** [comment]
> 我自己尝试复现了，没用出现。你用的是带管理员权限的Traffic Monitor对吧？ 个人觉得这个似乎不是本程序的问题。如果可以的话你可以测试一下别的插件保存配置是否可用如何？

你在复现时有尝试删除插件目录下的配置文件再启动程序吗？因为目前的行为似乎是启动时加载的是插件目录下的配置文件，如果这个配置文件内容和AppData中的配置文件内容相同的话就看不出来了。

**Comment by AzulEterno** [comment]
> > 我自己尝试复现了，没用出现。你用的是带管理员权限的Traffic Monitor对吧？ 个人觉得这个似乎不是本程序的问题。如果可以的话你可以测试一下别的插件保存配置是否可用如何？
> 
> 你在复现时有尝试删除插件目录下的配置文件再启动程序吗？因为目前的行为似乎是启动时加载的是插件目录下的配置文件，如果这个配置文件内容和AppData中的配置文件内容相同的话就看不出来了。

搞定了，其实原因挺奇葩的。 但是还是搞定了。初始化的时候读取配置的工作流在加载功耗监测之后导致的。那个额外配置文件本来是为了提前工作流的导致了初始化了一个错误的配置文件保存。现在应该完全正常了。

**Comment by FrzMtrsprt** [comment]
正常了，感谢
