### ISSUE TITLE
检测不到电池功耗

### ISSUE THREAD

**Issue by IDKHugh** [AzulEterno/Plugins-For-TrafficMonitor#3]
<img width="52" alt="屏幕截图 2022-04-26 000943" src="https://user-images.githubusercontent.com/98767047/165129413-6d91ac10-b3b4-4fc9-8ac2-cb1e25a9c691.png">
双击后弹出：

<img width="315" alt="屏幕截图 2022-04-26 001038" src="https://user-images.githubusercontent.com/98767047/165129577-3944fd65-d583-4003-8813-b0806a6c0d14.png">

**Comment by AzulEterno** [comment]
> <img alt="屏幕截图 2022-04-26 000943" width="52" src="https://user-images.githubusercontent.com/98767047/165129413-6d91ac10-b3b4-4fc9-8ac2-cb1e25a9c691.png">
> 
> 双击后弹出：
> <img alt="屏幕截图 2022-04-26 001038" width="315" src="https://user-images.githubusercontent.com/98767047/165129577-3944fd65-d583-4003-8813-b0806a6c0d14.png">

更新一下现在的版本。

**Comment by IDKHugh** [comment]
>

**Comment by IDKHugh** [comment]
> > <img alt="屏幕截图 2022-04-26 000943" width="52" src="https://user-images.githubusercontent.com/98767047/165129413-6d91ac10-b3b4-4fc9-8ac2-cb1e25a9c691.png">
> > 双击后弹出： 
> > <img alt="屏幕截图 2022-04-26 001038" width="315" src="https://user-images.githubusercontent.com/98767047/165129577-3944fd65-d583-4003-8813-b0806a6c0d14.png">
> 
> 更新一下现在的版本。

[PowerMonPlugin.dll]没有看到新的releases，TrafficMonitor已经是最新版本了。请问我需要更新什么？
<img width="934" alt="屏幕截图 2022-04-26 091749" src="https://user-images.githubusercontent.com/98767047/165199811-3cd28812-f176-4c74-8c29-6a5af6bf38db.png">
<img width="373" alt="屏幕截图 2022-04-26 091548" src="https://user-images.githubusercontent.com/98767047/165199875-30bfda32-227c-4ae8-b4cb-2a4a29e8ea0e.png">

**Comment by AzulEterno** [comment]
插件需要单独到源下载地址更新。
这个检测更新只是TrafficMonitor本身的。

**Comment by IDKHugh** [comment]
是的，请查看这张图片
我没有收到PowerMonPlugin.dll新的releases
<img width="934" alt="屏幕截图 2022-04-26 091749" src="https://user-images.githubusercontent.com/98767047/165200264-fe6c819b-8075-4ad8-b819-d7990b818c23.png">

**Comment by IDKHugh** [comment]
> 插件需要单独到源下载地址更新。 这个检测更新只是TrafficMonitor本身的。

请问在哪里更新您提到的新版本呢？我现在安装的已经是仓库里最新的了（2022年3月6日）
![图片](https://user-images.githubusercontent.com/98767047/165206429-563fccab-ea5d-470a-9793-d833975dd143.png)

**Comment by AzulEterno** [comment]
> > 插件需要单独到源下载地址更新。 这个检测更新只是TrafficMonitor本身的。
> 
> 请问在哪里更新您提到的新版本呢？我现在安装的已经是仓库里最新的了（2022年3月6日） ![图片](https://user-images.githubusercontent.com/98767047/165206429-563fccab-ea5d-470a-9793-d833975dd143.png)

重新同步了生成结果。之前代理出了点问题可能导致新版本没有同步的上。

**Comment by IDKHugh** [comment]
问题依旧存在，详细信息里能看到电池电压&剩余电量，但功耗为0。一个很实用的插件，希望能够被您修复。
![图片](https://user-images.githubusercontent.com/98767047/165211677-fcfa6b39-f2e2-488a-b7d0-78606905ae93.png)

**Comment by AzulEterno** [comment]
> 问题依旧存在，详细信息里能看到电池电压&剩余电量，但功耗为0。一个很实用的插件，希望能够被您修复。 ![图片](https://user-images.githubusercontent.com/98767047/165211677-fcfa6b39-f2e2-488a-b7d0-78606905ae93.png)

见[这里](https://github.com/AzulEterno/Plugins-For-TrafficMonitor/issues/2)
